# Generated by Django 4.1.3 on 2022-11-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "roll",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("parentName", models.CharField(max_length=100)),
                ("course", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserInput",
            fields=[
                (
                    "roll",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("subject1", models.CharField(max_length=100)),
                ("maxMarkSub1", models.IntegerField()),
                ("markObSub1", models.IntegerField()),
                ("subject2", models.CharField(max_length=100)),
                ("maxMarkSub2", models.IntegerField()),
                ("markObSub2", models.IntegerField()),
                ("subject3", models.CharField(max_length=100)),
                ("maxMarkSub3", models.IntegerField()),
                ("markObSub3", models.IntegerField()),
                ("subject4", models.CharField(max_length=100)),
                ("maxMarkSub4", models.IntegerField()),
                ("markObSub4", models.IntegerField()),
                ("subject5", models.CharField(max_length=100)),
                ("maxMarkSub5", models.IntegerField()),
                ("markObSub5", models.IntegerField()),
                ("subject6", models.CharField(max_length=100)),
                ("maxMarkSub6", models.IntegerField()),
                ("markObSub6", models.IntegerField()),
            ],
        ),
    ]
