# Generated by Django 4.1.3 on 2022-11-09 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student_marksheet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinput",
            name="userdata",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_marksheet.userdata",
            ),
        ),
    ]
