# Generated by Django 4.2.5 on 2023-10-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_marksheet', '0002_userinput_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='roll',
            field=models.CharField(default='P111-22', max_length=100, primary_key=True, serialize=False),
        ),
    ]
