# Generated by Django 4.2.5 on 2023-10-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_marksheet', '0003_alter_userdata_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
