# Generated by Django 4.2.5 on 2023-10-13 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student_marksheet', '0006_logo_userdata_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
